name: publish

on:
  push:
    branches:
      - main
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Enable actions unsecure commands
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: Checkout The Code
        uses: actions/checkout@v2.1.1
      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: update the module version
        run: npm version minor
      - name: publish the module to the node package manager
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
